version: '3.8'

services:
  db:
    image: postgres:15
    container_name: stackcrm-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackcrm
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: stackcrm-api
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/stackcrm
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  db-data:
